set(CMAKE_SYSTEM_NAME Darwin)

set(CMAKE_EXPERIMENTAL_CXX_IMPORT_STD "0e5b6991-d74f-4b3d-a41c-cf096e0b2508")
set(CMAKE_CXX_MODULE_STD 1)

set(CMAKE_C_COMPILER $ENV{INSTP}/bin/clang)
set(CMAKE_CXX_COMPILER $ENV{INSTP}/bin/clang++)

set(CMAKE_EXE_LINKER_FLAGS_INIT
  "-L$ENV{INSTP}/lib \
  -Wl,-rpath,$ENV{INSTP}/lib \
  -fuse-ld=lld")
